name: CI
on: [push]

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup backend environment
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore deps cache
        uses: actions/cache@v4
        id: mix_cache
        with:
          path: |
            deps
            _build
          key: test-${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}

      - name: Install Elixir Dependencies
        if: steps.mix_cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      # You might want to add `--warnings-as-errors` here
      - name: Compile app
        run: mix compile

      - name: Check formatting
        run: mix format --check-formatted

      - name: Test app
        run: mix test

      - name: Check for transitive compilation dependencies
        run: mix xref graph --label compile-connected --fail-above 5
